version: '3.7'

services: 
  django_gunicorn:
    volumes: 
      - static:/staticfiles
    env_file:
      - .env
    build:
      context: .
    ports: 
      - "8000:8000"
    networks: 
      - main
  nginx:
    build: ./nginx
    volumes: 
      - static:/staticfiles
    ports: 
      - "8080:8080"
    depends_on: 
      - django_gunicorn
    networks: 
      - main

volumes: 
  static:
networks: 
  main:
